export interface Machine {
    id?: string;
    badge?: string;
    size?: string;
    color?: string;
    make?: string;
    model?: string;
    drumunit?: string;
    developerunit?: string;
    wtc?: string;
    fuserunit?: string;
    itb?: string;
    itbcleaner?: string;
    transferrollerptb?: string;
    feedrollerstray?: string;
    separationrollertray?: string;
    feedrollersbypass?: string;
    adfpickup?: string;
    adfreversefriction?: string;
    lsu?: string;
    platen?: string;
    pbamain?: string;
    opepba?: string;
    smps?: string;
    hvps?: string;
    ope?: string;
    hdd?: string;
    observations?: string;
  }
